---
title: "Exercise 1"
output: 
  html_document: 
    number_sections: true
    toc: true
---

# Exercise 2

# Introduction

In the second exercise, you will apply what you learnt in exercise 1 to annotate a breast cancer dataset.

```{r, message=FALSE, warning=F, results=FALSE}

# Load the environment and libraries
# install.packages("remotes")
# library(remotes)
# remotes::install_github("carmonalab/scGate",ref="7a3576d")
# remotes::install_github("carmonalab/SignatuR",ref="b1050ae32a600b986f14db236f8d45756aaee05b")
# remotes::install_github("carmonalab/STACAS",ref="05fa74d")
# remotes::install_github("carmonalab/scIntegrationMetrics")
library(Seurat)
library(scGate)
library(SignatuR)
library(STACAS)
library(scIntegrationMetrics)
library(ggplot2)
library(dplyr)
library(patchwork)
library(parallel)

# devtools::install_github('satijalab/seurat-data')
library(SeuratData)
```

# Set paths
```{r}
my_seed <- 321
set.seed(my_seed)

root <- getwd()

path_data <- file.path(root, "data")
dir.create(file.path(path_data))
path_output <- file.path(root, "output")
dir.create(file.path(path_output))
path_plots <- file.path(root, "plots")
dir.create(file.path(path_plots))
```


# Load the data

```{r, fig.height=10, fig.width=10}
InstallData("panc8")
data("panc8")
panc8 <-  UpdateSeuratObject(object = panc8)

ndim <- 30
panc8 <- panc8 |> NormalizeData() |> FindVariableFeatures() |> ScaleData() |> RunPCA(npcs=ndim) |> RunUMAP(reduction = "pca", dims = 1:ndim, seed.use=my_seed)

p.list.Tcell <- list()
p.list.Tcell[[1]] <- DimPlot(panc8, label = T, repel = T, group.by = 'celltype')
p.list.Tcell[[2]] <- DimPlot(panc8, label = T, repel = T, group.by = 'tech')
p.list.Tcell[[3]] <- DimPlot(panc8, label = T, repel = T, group.by = 'dataset')
for (p in p.list.Tcell) {
  print(p)
}
wrap_plots(p.list.Tcell, ncol = 2) & theme(aspect.ratio = 1) & NoLegend()
```


# Apply batch correction

```{r}
panc8.list <- SplitObject(panc8, split.by = "tech")
panc8.stacas <- Run.STACAS(panc8.list)
```


# Investigate the effect of batch correction

```{r, fig.height=10, fig.width=10}
panc8.stacas <- RunUMAP(panc8.stacas, reduction = "pca", dims = 1:ndim, seed.use=my_seed)

p.list.Tcell <- list()
p.list.Tcell[[1]] <- DimPlot(panc8.stacas, label = T, repel = T, group.by = 'celltype')
p.list.Tcell[[2]] <- DimPlot(panc8.stacas, label = T, repel = T, group.by = 'tech')
p.list.Tcell[[3]] <- DimPlot(panc8.stacas, label = T, repel = T, group.by = 'dataset')
for (p in p.list.Tcell) {
  print(p)
}
wrap_plots(p.list.Tcell, ncol = 2) & theme(aspect.ratio = 1) & NoLegend()
```


```{r}
Idents(panc8.stacas) <- "celltype"
dist.matrix <- dist(Embeddings(object = panc8[["pca"]])[, 1:ndim])
clusters <- panc8$celltype
sil <- cluster::silhouette(as.numeric(as.factor(clusters)), dist = dist.matrix)
panc8$sil <- sil[, "sil_width"]

celltype_means_before <- c()
dataset_means_before <- c()
for (tech in unique(panc8$tech)) {
  a <- c()
  for (celltype in unique(panc8$celltype)) {
    b <- mean(panc8$sil[panc8$tech == tech & panc8$celltype == celltype])
    a <- append(a, b)
    celltype_means_before <- append(celltype_means_before, b)
  }
  dataset_means_before <- append(dataset_means_before, mean(a))
  print(mean(a))
}
mean(dataset_means_before)
mean(celltype_means_before)


Idents(panc8.stacas) <- "celltype"
dist.matrix <- dist(Embeddings(object = panc8.stacas[["pca"]])[, 1:ndim])
clusters <- panc8.stacas$celltype
sil <- cluster::silhouette(as.numeric(as.factor(clusters)), dist = dist.matrix)
panc8.stacas$sil <- sil[, "sil_width"]

celltype_means_after <- c()
dataset_means_after <- c()
for (tech in unique(panc8.stacas$tech)) {
  a <- c()
  for (celltype in unique(panc8.stacas$celltype)) {
    b <- mean(panc8.stacas$sil[panc8.stacas$tech == tech & panc8.stacas$celltype == celltype])
    a <- append(a, b)
    celltype_means_after <- append(celltype_means_after, b)
  }
  dataset_means_after <- append(dataset_means_after, mean(a))
  print(mean(a))
}
mean(dataset_means_after)
mean(celltype_means_after)
```


# Re-calculate integration metrics after batch correction

```{r}
metrics <- getIntegrationMetrics(panc8, meta.label = "celltype",
                                 meta.batch = "tech",
                                 iLISI_perplexity = 20)
unlist(metrics)

metrics <- getIntegrationMetrics(panc8.stacas, meta.label = "celltype",
                                 meta.batch = "tech",
                                 iLISI_perplexity = 20)
unlist(metrics)
```